add v2 with generics
go-pkgz/lcw pull request #43
Opened 2024-02-18 18:36 UTC by paskal

2024-02-18 21:39 UTC, umputun commented on v2/go.mod
> +toolchain go1.21.6
this better to be removed, we don't want to enforce toolchain version especially for the library

2024-02-18 21:51 UTC, umputun commented
Looking good. I'm not a big fan of using reflection for Redis, but it's likely the right approach in this situation. Please ping me once you're done with everything, and I'll take a closer look.

2024-02-18 21:57 UTC, paskal commented
@umputun, everything is ready for review. It took some time for me to figure out how to combine two coverage profiles into one for a proper coverage report.

2024-02-19 17:26 UTC, umputun requested changes
A couple of things:

- lint/style: imports are not sorted properly, one of file has import twice
- attempt to `go get -u ./...` brings redis's lib update, and it seems to be incompatible with our code

2024-02-19 18:28 UTC, paskal commented
The Redis problem seems to be https://github.com/redis/go-redis/issues/2914. It should be fixed upstream, as it affects a lot of cases.

2024-02-20 18:09 UTC, umputun approved these changes
LGTM

2024-02-20 18:24 UTC, merged